version: '3.7'

services:
  localstack:
    image: localstack/localstack:1.4.0
    environment:
      - SERVICES=s3,sqs,sns
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-1
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - localstackdata:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  localstack-setup:
    depends_on:
      - localstack
    build:
      context: ./localstack-setup
    environment:
      - AWS_REGION=eu-west-1
      - AWS_SECRET_ACCESS_KEY=DUMMY_KEY
      - AWS_ACCESS_KEY_ID=DUMMY_KEY

  payments.db:
    image: mysql:5.7
    ports:
      - "33061:3306"
    volumes:
      - paymentsappdbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=defaultdb
      - MYSQL_ROOT_PASSWORD=Password123
  
  payments.db.migrations:
    depends_on:
      - payments.db
    image: payments.db.migrations
    build:
      context: ./db/
      dockerfile: Dockerfile
    command: -cs "server=payments.db;database=defaultdb;uid=root;password=Password123;SslMode=None;"

  seq:
    image: datalust/seq:2023.1
    ports:
      - "8080:80"
      - "5341:5341"
    volumes:
      - /datadrive:/data
    environment:
      - ACCEPT_EULA=Y
      - BASE_URI=https://seq.dptsprotrans.com

  acquiringbank.api:
    image: acquiringbank.api
    build:
      context: .
      dockerfile: src/AcquiringBank.Api/Dockerfile
    ports:
      - "4000:80"

  payments.api:
    depends_on:
      - payments.db
      - localstack
      - acquiringbank.api
      - payments.db.migrations
      - localstack-setup
      - seq
    image: payments.api
    build:
      context: .
      dockerfile: src/Payments.Api/Dockerfile
    environment:
      - RUNNINGINCONTAINER=1
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTPS_PORT=44374
      - AWS_REGION=eu-west-1
      - AWS_SECRET_ACCESS_KEY=DUMMY_KEY
      - AWS_ACCESS_KEY_ID=DUMMY_KEY
      - DATABASE__SERVER=payments.db
      - DATABASE__PORT=3306
      - DATABASE__SSLMODE=None
      - NSERVICEBUS__SqsServiceUrlOverride=http://localstack:4566
      - NSERVICEBUS__S3ServiceUrlOverride=http://localstack:4566
      - NSERVICEBUS__SnsServiceUrlOverride=http://localstack:4566
      - SEQ_SERVER_URL=http://seq:5341
    ports:
      - "5000:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  payments.host:
    depends_on:
      - payments.db
      - localstack
      - acquiringbank.api
      - payments.db.migrations
      - localstack-setup
      - seq
    image: payments.host
    build:
      context: .
      dockerfile: src/Payments.Host/Dockerfile
    environment:
      - RUNNINGINCONTAINER=1
      - DATABASE__SERVER=payments.db
      - DATABASE__PORT=3306
      - DATABASE__SSLMODE=None
      - AWS_REGION=eu-west-1
      - AWS_SECRET_ACCESS_KEY=DUMMY_KEY
      - AWS_ACCESS_KEY_ID=DUMMY_KEY
      - ACQUIRINGBANK__BASEURL=http://acquiringbank.api
      - NSERVICEBUS__SqsServiceUrlOverride=http://localstack:4566
      - NSERVICEBUS__S3ServiceUrlOverride=http://localstack:4566
      - NSERVICEBUS__SnsServiceUrlOverride=http://localstack:4566
      - SEQ_SERVER_URL=http://seq:5341

volumes:
  localstackdata:
  paymentsappdbdata:
