USE Payments;

CREATE TABLE IF NOT EXISTS Payment (
    ClusteredId INT NOT NULL PRIMARY KEY,
    Id CHAR(36) NOT NULL UNIQUE,
    CreatedOn DATETIME NOT NULL,
    UpdatedOn DATETIME NOT NULL
) ENGINE=INNODB;